# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b37cfede25b5d6021769e9fd935fe8c8e4cf5afd7be19e1b3f054ba8f8cc8f5f4dada8304c6616a422a03d9735a4ed31343724944f44c3f7cb2f08087881bbb8

test:
  secret_key_base: 2e769aeddc69c20a951f28684ea67abe3fddba7b84434f0b87628f9453386666546a92bd0c41cda2d07d5a5e65eb09a6f798cb92a44d84f50701aa12b026ec50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
